services:
  - type: web
    name: daily-bot-1
    runtime: python
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: TOKEN_1

  - type: web
    name: daily-bot-2
    runtime: python
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: TOKEN_2

  - type: web
    name: daily-bot-3
    runtime: python
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: TOKEN_3
